# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the ordinary least squares.
#' 
#' @param D the the response vector
#' @param W the the predictor vector
#' @return the estamated regression coefficients
naiveRegression <- function(D, W) {
    .Call('_measError_naiveRegression', PACKAGE = 'measError', D, W)
}

#' Compute the moment corrected estimator for the simple linear regression.
#' 
#' @param D the the response vector
#' @param W the the predictor vector
#' @param sigmaU the measurement uncertainty vector for the predictor
#' @return the estamated regression coefficients
#' @examples
#' library(measError)
#' set.seed(100)
#' n = 400
#' beta0 = 1
#' beta1 = 2
#' sigmaU = runif(n, 0.4, 0.6)
#' sigmaQ = runif(n, 0.1, 0.2)
#' sigmaE = 0.2
#' simuData = getData(n, beta0, beta1, sigmaU, sigmaQ, sigmaE)
#' (betaHat1 = naiveRegression(simuData$D, simuData$W))
#' (betaHat2 = correctedRegression(simuData$D, simuData$W, sigmaU))
correctedRegression <- function(D, W, sigmaU) {
    .Call('_measError_correctedRegression', PACKAGE = 'measError', D, W, sigmaU)
}

